# Generated by Django 5.2.5 on 2025-09-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_request_current_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesthistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'ایجاد درخواست'), ('APPROVED', 'تایید و ارسال به مرحله بعد'), ('REJECTED', 'درخواست رد شد'), ('COMMENTED', 'نظر ثبت شد')], max_length=50, verbose_name='نوع اقدام'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.processstep', verbose_name='مرحله'),
        ),
    ]
