# Generated by Django 5.2.6 on 2025-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requesthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'ایجاد درخواست'), ('APPROVED', 'تایید و ارسال به مرحله بعد'), ('REJECTED', 'درخواست رد شد'), ('COMMENTED', 'نظر ثبت شد'), ('RETURNED', 'بازگردانده شد'), ('RESUBMITTED', 'مجدداً ارسال شد')], max_length=50, verbose_name='نوع اقدام'),
        ),
    ]
