# Generated by Django 5.2.6 on 2025-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requesthistory_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='فایل پیوست'),
        ),
    ]
