# Generated by Django 5.2.6 on 2025-09-07 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requesthistory_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='deadline_days',
            field=models.PositiveIntegerField(default=3, help_text='تعداد روز مجاز برای انجام این مرحله.', verbose_name='مهلت انجام (به روز)'),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='پیام اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request', verbose_name='درخواست مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
