# Generated by Django 5.2.6 on 2025-09-09 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processstep_deadline_days_request_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='current_assignee',
        ),
        migrations.RemoveField(
            model_name='request',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='request',
            name='due_date',
        ),
        migrations.CreateModel(
            name='ActiveStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار اقدام'), ('COMPLETED', 'تکمیل شده')], default='PENDING', max_length=20, verbose_name='وضعیت وظیفه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.processstep', verbose_name='مرحله فرایند')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_steps', to='core.request', verbose_name='درخواست')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
