# Generated by Django 5.2.6 on 2025-09-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_request_current_assignee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activestep',
            options={'ordering': ['-created_at'], 'verbose_name': 'وظیفه فعال', 'verbose_name_plural': 'وظایف فعال'},
        ),
        migrations.AlterField(
            model_name='processstep',
            name='step_order',
            field=models.PositiveIntegerField(help_text='مراحلی که شماره ترتیب یکسان دارند به صورت موازی اجرا می\u200cشوند.', verbose_name='ترتیب مرحله'),
        ),
    ]
