# Generated by Django 5.2.6 on 2025-09-09 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_activestep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول فعلی'),
        ),
        migrations.AddField(
            model_name='request',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.processstep', verbose_name='مرحله فعلی'),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='step_order',
            field=models.PositiveIntegerField(verbose_name='ترتیب مرحله'),
        ),
        migrations.DeleteModel(
            name='ActiveStep',
        ),
    ]
