# Generated by Django 5.2.6 on 2025-09-09 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_request_current_assignee_request_current_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='current_assignee',
        ),
        migrations.RemoveField(
            model_name='request',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='request',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='processstep',
            name='step_order',
            field=models.PositiveIntegerField(help_text='مراحلی که شماره ترتیب یکسان دارند به صورت موازی اجرا می\u200cشوند.', verbose_name='ترتیب مرحله'),
        ),
        migrations.CreateModel(
            name='ActiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار اقدام'), ('COMPLETED', 'تکمیل شده')], default='PENDING', max_length=20, verbose_name='وضعیت وظیفه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.processstep', verbose_name='مرحله فرایند')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_tasks', to='core.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'وظیفه فعال',
                'verbose_name_plural': 'وظایف فعال',
                'ordering': ['-created_at'],
            },
        ),
    ]
